/* ============================================
   Constants, presets, and reference data
   ============================================ */

const PLANETARY_BODIES = {
  earth: {
    label: 'Earth',
    cycleHours: 24,
    cyclesPerEarthYear: 365,
    cycleUnit: 'day',
    cycleUnitCompact: 'day',
    hoursPerCycleLabel: 'hrs/day',
    chartLabelMode: 'clock',
    supportsSpecificDay: true,
    chartNote: '',
    siteYieldNote: 'For more accurate Earth output, use a cloud/weather-adjusted source such as PVGIS or Global Solar Atlas PVOUT.',
  },
  mars: {
    label: 'Mars',
    cycleHours: 24.66,
    cyclesPerEarthYear: 355,
    cycleUnit: 'sol',
    cycleUnitCompact: 'sol',
    hoursPerCycleLabel: 'hrs/sol',
    chartLabelMode: 'clock',
    supportsSpecificDay: false,
    chartNote: 'Representative average local-sol profile; annual dispatch includes modeled Mars orbital seasonality. Annual economics remain normalized to an Earth year.',
    siteYieldNote: 'Mars presets use literature-inspired annual-yield benchmarks; Earth cloud datasets and latitude heuristics are disabled.',
  },
  moon: {
    label: 'Moon',
    cycleHours: 708.7,
    cyclesPerEarthYear: 12.37,
    cycleUnit: 'lunar cycle',
    cycleUnitCompact: 'cycle',
    hoursPerCycleLabel: 'hrs/cycle',
    chartLabelMode: 'days',
    supportsSpecificDay: false,
    chartNote: 'Representative south-polar ridge profile: mostly-on illumination with terrain-shadow dips and brief outages, not a clean two-week day/night cycle. Mounting still matters because the Sun stays low on the horizon. Annual economics remain normalized to an Earth year.',
    siteYieldNote: 'Lunar presets use literature-inspired annual-yield benchmarks; Earth cloud datasets and latitude heuristics are disabled.',
  },
};

const LOCATION_PRESETS = [
  {
    name: 'Mars - Noctis Labyrinthus',
    body: 'mars',
    profile: 'mars-average',
    lat: -7.0,
    lon: -102.0,
    ghi: 900,
    baseYield: 1150,
    region: 'planetary',
  },
  {
    name: 'Moon - South Pole Peak of Eternal Light',
    body: 'moon',
    profile: 'lunar-pel',
    lat: -89.5,
    lon: 0.0,
    ghi: 3200,
    baseYield: 3000,
    region: 'planetary',
  },
  { name: 'Los Angeles, CA', lat: 34.05, lon: -118.24, ghi: 2050, baseYield: 1680, region: 'desert' },
  { name: 'Phoenix, AZ', lat: 33.45, lon: -112.07, ghi: 2380, baseYield: 1940, region: 'desert' },
  { name: 'Mojave Desert, CA', lat: 35.05, lon: -117.60, ghi: 2450, baseYield: 2050, region: 'desert' },
  { name: 'Atacama, Chile', lat: -24.50, lon: -69.25, ghi: 2800, baseYield: 2300, region: 'desert' },
  { name: 'Sahara (Algeria)', lat: 30.05, lon: 2.88, ghi: 2500, baseYield: 2100, region: 'desert' },
  { name: 'Rajasthan, India', lat: 26.92, lon: 70.90, ghi: 2200, baseYield: 1820, region: 'desert' },
  { name: 'Pilbara, Australia', lat: -22.30, lon: 118.30, ghi: 2400, baseYield: 1980, region: 'desert' },
  { name: 'Dubai, UAE', lat: 25.20, lon: 55.27, ghi: 2150, baseYield: 1780, region: 'desert' },
  { name: 'Austin, TX', lat: 30.27, lon: -97.74, ghi: 1900, baseYield: 1550, region: 'temperate' },
  { name: 'Denver, CO', lat: 39.74, lon: -104.99, ghi: 1950, baseYield: 1640, region: 'temperate' },
  { name: 'Miami, FL', lat: 25.76, lon: -80.19, ghi: 1800, baseYield: 1475, region: 'tropical' },
  { name: 'Madrid, Spain', lat: 40.42, lon: -3.70, ghi: 1850, baseYield: 1530, region: 'temperate' },
  { name: 'Berlin, Germany', lat: 52.52, lon: 13.41, ghi: 1050, baseYield: 890, region: 'cloudy' },
  { name: 'London, UK', lat: 51.51, lon: -0.13, ghi: 950, baseYield: 790, region: 'cloudy' },
  { name: 'Tokyo, Japan', lat: 35.68, lon: 139.69, ghi: 1350, baseYield: 1120, region: 'temperate' },
  { name: 'Nairobi, Kenya', lat: -1.29, lon: 36.82, ghi: 2000, baseYield: 1660, region: 'tropical' },
  { name: 'São Paulo, Brazil', lat: -23.55, lon: -46.63, ghi: 1600, baseYield: 1320, region: 'tropical' },
  { name: 'Beijing, China', lat: 39.90, lon: 116.40, ghi: 1400, baseYield: 1180, region: 'temperate' },
  { name: 'Reykjavik, Iceland', lat: 64.15, lon: -21.94, ghi: 750, baseYield: 620, region: 'cloudy' },
  { name: 'Cape Town, SA', lat: -33.93, lon: 18.42, ghi: 1950, baseYield: 1620, region: 'temperate' },
];

const MOUNTING_TYPES = {
  fixed: {
    label: 'Fixed Tilt',
    yieldMult: 1.0,
    landPacking: 1.0,
    windRating: '130 mph',
    typicalBOS: 0.20,
    note: 'Simple baseline for generic utility-scale PV.',
  },
  ew: {
    label: 'East-West Fixed',
    yieldMult: 0.92,
    landPacking: 2.25,
    windRating: '180 mph (vendor claim class)',
    typicalBOS: 0.12,
    note: 'High-density low-tilt layout inspired by PEG-style systems with a broader two-shoulder daily profile.',
  },
  single: {
    label: 'Single-Axis Tracker',
    yieldMult: 1.18,
    landPacking: 0.90,
    windRating: '120 mph',
    typicalBOS: 0.35,
    note: 'Higher yield, higher BOS, more land, stronger weather dependence, and a flatter tracked daily profile.',
  },
  dual: {
    label: 'Dual-Axis Tracker',
    yieldMult: 1.28,
    landPacking: 0.60,
    windRating: '90 mph',
    typicalBOS: 0.55,
    note: 'Comparison only. Not part of the Terraform-style thesis.',
  },
};

const CHEMISTRY = {
  electrolysis: {
    theoreticalMinimum: 39.4,
    h2EnergyContent: 33.33,
    waterPerKgH2: 9,
  },
  dac: {
    co2MolarMass: 44.01,
    atmosphericCO2ppm: 420,
    calcinationTemp: 900,
  },
  sabatier: {
    ch4MolarMass: 16.04,
    ch4PerMCF: 19.25,
    h2MassPerKgCH4: 0.503,
    co2MassPerKgCH4: 2.744,
    waterPerKgCH4: 2.25,
  },
  methanol: {
    molarMass: 32.04,
    h2MassPerKgMeOH: 0.189,
    co2MassPerKgMeOH: 1.374,
    waterPerKgMeOH: 0.562,
    density: 0.792,
  },
};

const POLICY_CREDITS = {
  us_45v_tier4: 3.00,
  us_45v_tier3: 1.00,
  us_45v_tier2: 0.75,
  us_45v_tier1: 0.60,
  us_45q_utilization: 130,
  us_45q_sequestration: 180,
};

const POLICY_OPTIONS = {
  none: {
    label: 'No policy credits',
    applicability: 'None selected',
    basis: 'Pure market revenue only',
    note: 'No federal production credits are applied. US 45V and 45Q presets are available under Policy Mode when you want to explore those cases.',
    stackingRule: 'No policy credit selected',
    useCustomH2: false,
    useCustomCo2: false,
  },
  us_45v_tier4: {
    label: 'US 45V clean H2 - Tier 4',
    applicability: 'United States',
    basis: 'Top-tier 45V credit, modeled at $3.00/kg H2 for eligible hydrogen production over 10 years',
    note: 'Use this only for top-tier US clean hydrogen cases. Treasury final rules require lifecycle qualification plus incrementality, deliverability, and temporal matching for EAC-based electrolytic claims.',
    stackingRule: 'Modeled as mutually exclusive with US 45Q for the same facility',
    h2Credit: POLICY_CREDITS.us_45v_tier4,
    useCustomH2: false,
    useCustomCo2: false,
    durationYears: 10,
  },
  us_45v_tier3: {
    label: 'US 45V clean H2 - Tier 3',
    applicability: 'United States',
    basis: 'Mid-tier 45V credit, modeled at $1.00/kg H2 for 0.45-1.5 kg CO2e/kg H2 cases',
    note: 'Use when the US project qualifies for the third 45V emissions tier rather than the top tier.',
    stackingRule: 'Modeled as mutually exclusive with US 45Q for the same facility',
    h2Credit: POLICY_CREDITS.us_45v_tier3,
    useCustomH2: false,
    useCustomCo2: false,
    durationYears: 10,
  },
  us_45v_tier2: {
    label: 'US 45V clean H2 - Tier 2',
    applicability: 'United States',
    basis: 'Mid-tier 45V credit, modeled at $0.75/kg H2 for 1.5-2.5 kg CO2e/kg H2 cases',
    note: 'Use when the US project qualifies for the second 45V emissions tier.',
    stackingRule: 'Modeled as mutually exclusive with US 45Q for the same facility',
    h2Credit: POLICY_CREDITS.us_45v_tier2,
    useCustomH2: false,
    useCustomCo2: false,
    durationYears: 10,
  },
  us_45v_tier1: {
    label: 'US 45V clean H2 - Tier 1',
    applicability: 'United States',
    basis: 'Entry-tier 45V credit, modeled at $0.60/kg H2 for 2.5-4.0 kg CO2e/kg H2 cases',
    note: 'Use when the US project qualifies for the first 45V emissions tier.',
    stackingRule: 'Modeled as mutually exclusive with US 45Q for the same facility',
    h2Credit: POLICY_CREDITS.us_45v_tier1,
    useCustomH2: false,
    useCustomCo2: false,
    durationYears: 10,
  },
  us_45q_utilization: {
    label: 'US 45Q DAC utilization',
    applicability: 'United States',
    basis: 'DAC utilization credit modeled at $130/t-CO2 for qualifying US projects',
    note: 'This is the post-IRA DAC utilization value commonly cited by Terraform for US projects that use captured CO2 rather than sequestering it.',
    stackingRule: 'Modeled as mutually exclusive with US 45V for the same facility',
    co2Credit: POLICY_CREDITS.us_45q_utilization,
    useCustomH2: false,
    useCustomCo2: false,
  },
  us_45q_sequestration: {
    label: 'US 45Q DAC sequestration',
    applicability: 'United States',
    basis: 'DAC sequestration credit modeled at $180/t-CO2 for qualifying US projects',
    note: 'Use this only for US sequestration cases, not for methane synthesis or other CO2 utilization pathways.',
    stackingRule: 'Modeled as mutually exclusive with US 45V for the same facility',
    co2Credit: POLICY_CREDITS.us_45q_sequestration,
    useCustomH2: false,
    useCustomCo2: false,
  },
  eu_hydrogen_bank: {
    label: 'EU Hydrogen Bank premium',
    applicability: 'European Union; 2026 auction rounds also include Germany and Spain top-up budgets via Auctions-as-a-Service',
    basis: 'User-entered fixed premium on verified hydrogen production for up to 10 years',
    note: 'This is not a single statutory EU-wide amount. Enter your assumed bid premium in the model currency; early winning bids were far below the ceiling and country top-ups still flow through the auction mechanism.',
    stackingRule: 'Modeled here as one bid-based H2 premium rather than a stack of separate EU and member-state credits',
    useCustomH2: true,
    useCustomCo2: false,
    h2InputLabel: 'EU H2 Premium ($/kg equivalent)',
    durationYears: 10,
  },
  custom: {
    label: 'Custom / country-specific credits',
    applicability: 'User-defined',
    basis: 'User-entered H2 and CO2 credits for country-specific or stacked cases',
    note: 'Use this for country programs or contract structures that are not captured by the named US and EU presets.',
    stackingRule: 'Custom mode can stack user-defined H2 and CO2 credits',
    useCustomH2: true,
    useCustomCo2: true,
    h2InputLabel: 'Custom H2 Credit ($/kg)',
    co2InputLabel: 'Custom CO2 Credit ($/ton)',
  },
};

const METHANE_MARKET_PRESETS = {
  terraform_commodity: {
    label: 'Commodity gas / whitepaper-style case',
    applicability: 'Generic / multi-country',
    basis: 'Simple sale-price assumption for commodity methane; Terraform public materials often illustrate a roughly $10/MCF case before incentives',
    note: 'Use this when you want an unsubsidized commodity-gas framing rather than a country-specific biomethane support regime.',
  },
  premium_green_methane: {
    label: 'Premium synthetic / green methane offtake',
    applicability: 'Generic / voluntary premium markets',
    basis: 'Sale-price assumption for premium synthetic methane, biomethane, or low-carbon gas contracts',
    note: 'Use this for premium offtake scenarios such as green gas contracts. The slider should capture the net realized methane value.',
  },
  germany_biomethane_eeg: {
    label: 'Germany biomethane auction / EEG',
    applicability: 'Germany',
    basis: 'Bundesnetzagentur EEG biomethane auction framework; country-specific and tender-based rather than one universal methane subsidy',
    note: 'Germany has a specific biomethane tender framework, but it does not translate cleanly into one fixed $/MCF credit here. Keep the methane sale price manual and use the note as a country context label.',
  },
  netherlands_sdepp: {
    label: 'Netherlands renewable gas / SDE++',
    applicability: 'Netherlands',
    basis: 'SDE++ operating support for renewable gas injected into the network; effectively a difference-style support structure tied to market value',
    note: 'This is a Netherlands-specific operating support scheme rather than a single flat methane premium. Use the slider for your assumed net realized methane value or supported equivalent.',
  },
  denmark_green_gas_tender: {
    label: 'Denmark green gas tender',
    applicability: 'Denmark',
    basis: 'Danish Energy Agency tender framework for upgraded biogas and e-methane delivered to the gas grid',
    note: 'This is a Denmark-specific bid-based support structure with long support periods, so the app leaves the methane price manual instead of inventing a single default premium.',
  },
};

const MODEL_ASSUMPTIONS = {
  fallbackYieldFromGhi: 0.82,
  batteryNominalLifeYears: 12,
  batteryMonthlyLeakage: 0.02,
  fossilGasEmissionsPerMCF: 0.053,
};

const AI_COMPUTE_DEFAULTS = {
  capexPerKW: 50000,
  assetLifeYears: 5,
  omPercent: 4,
};

const AI_RELIABILITY_OPTIONS = [
  { value: 90, label: '90.0%' },
  { value: 95, label: '95.0%' },
  { value: 99, label: '99.0%' },
  { value: 99.5, label: '99.5%' },
  { value: 99.9, label: '99.9%' },
  { value: 99.95, label: '99.95%' },
  { value: 99.99, label: '99.99%' },
];

const MODULE_REGISTRY = [
  {
    id: 'electrolyzer',
    label: 'Electrolyzer',
    family: 'air-water-chemistry',
    maturity: 'Supported',
    kind: 'core',
    defaultEnabled: true,
    assetLifeKey: 'electrolyzerAssetLife',
    configs: [
      { key: 'electrolyzerEfficiency', label: 'Efficiency (kWh/kg H2)', type: 'range', min: 39, max: 100, step: 1, unit: 'kWh/kg' },
      { key: 'electrolyzerCapex', label: 'CAPEX ($/kW)', type: 'range', min: 10, max: 500, step: 10, unit: '$/kW' },
    ],
  },
  {
    id: 'dac',
    label: 'Direct Air Capture',
    family: 'calcination-minerals',
    maturity: 'Supported',
    kind: 'core',
    defaultEnabled: true,
    assetLifeKey: 'dacAssetLife',
    configs: [
      { key: 'dacEnergy', label: 'Efficiency (kWh/t-CO2)', type: 'range', min: 1000, max: 5000, step: 100, unit: 'kWh/t' },
      { key: 'dacCapex', label: 'CAPEX ($/kW)', type: 'range', min: 50, max: 5000, step: 50, unit: '$/kW' },
    ],
  },
  {
    id: 'sabatier',
    label: 'Methane (Sabatier)',
    family: 'air-water-chemistry',
    maturity: 'Supported',
    kind: 'product',
    dependencies: ['electrolyzer', 'dac'],
    order: 1,
    defaultEnabled: true,
    assetLifeKey: 'sabatierAssetLife',
    configs: [
      { key: 'sabatierConversion', label: 'Conversion Rate (%)', type: 'range', min: 80, max: 99.5, step: 0.5, unit: '%' },
      { key: 'sabatierCapex', label: 'CAPEX ($ per kg/h feed)', type: 'range', min: 20, max: 500, step: 5, unit: '$/kg-feed-hr' },
    ],
  },
  {
    id: 'methanol',
    label: 'Methanol',
    family: 'air-water-chemistry',
    maturity: 'Supported',
    kind: 'product',
    dependencies: ['electrolyzer', 'dac'],
    order: 2,
    defaultEnabled: false,
    assetLifeKey: 'methanolAssetLife',
    configs: [
      { key: 'methanolEfficiency', label: 'Conversion Rate (%)', type: 'range', min: 60, max: 95, step: 1, unit: '%' },
      { key: 'methanolCapex', label: 'CAPEX ($ per kg/h feed)', type: 'range', min: 50, max: 1000, step: 5, unit: '$/kg-feed-hr' },
    ],
  },
  {
    id: 'mtg',
    label: 'MTG (Methanol -> Gasoline)',
    family: 'air-water-chemistry',
    maturity: 'Exploratory',
    dependencies: ['methanol'],
    diagramInputs: {
      methanol: true,
    },
    routeOptions: [
      { value: 'fixed-bed', label: 'Fixed-bed MTG' },
      { value: 'fluid-bed', label: 'Fluid-bed MTG' },
    ],
    missingInputs: [
      'Gasoline vs total hydrocarbon basis and LPG / fuel-gas split',
      'Durene management, recycle-gas compression, and catalyst cycle length',
      'Minimum turndown, regeneration timing, and intermittent restart behavior',
    ],
  },
  {
    id: 'carbonMonoxide',
    label: 'CO2 -> CO',
    family: 'air-water-chemistry',
    maturity: 'Exploratory',
    dependencies: ['dac'],
    routeDependencies: {
      rwgs: ['electrolyzer'],
    },
    routeOptions: [
      { value: 'plasma', label: 'Plasma route (speculative)' },
      { value: 'rwgs', label: 'Reverse water-gas shift' },
      { value: 'low-temp-electrolysis', label: 'Low-temp CO2 electrolysis' },
      { value: 'soec-coelectrolysis', label: 'SOEC / co-electrolysis (developmental)' },
    ],
    missingInputs: [
      'DAC CO2 recycle ratio and CO purification spec',
      'Compression pressure, optional sacrificial carbon basis, and O2 handling',
      'Stack or reactor durability under hot cycling and intermittent dispatch',
    ],
  },
  {
    id: 'ammonia',
    label: 'Ammonia',
    family: 'air-water-chemistry',
    maturity: 'Exploratory',
    routeDependencies: {
      'haber-bosch': ['electrolyzer'],
    },
    routeOptions: [
      { value: 'haber-bosch', label: 'Haber-Bosch style loop' },
      { value: 'electrochemical', label: 'Electrochemical route (speculative)' },
    ],
    missingInputs: [
      'ASU type, N2 compression, argon purge, and NH3 condensation basis',
      'Loop minimum turndown, H2 buffer duration, and hot-standby energy',
      'Parallel-reactor flexibility assumptions for intermittent operation',
    ],
  },
  {
    id: 'specialtyCarbon',
    label: 'Specialty Electrocarbon',
    family: 'carbon-solids',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'molten-carbonate', label: 'Molten-carbonate electrolysis' },
      { value: 'graphene-grade', label: 'Graphene-grade polishing (speculative)' },
    ],
    missingInputs: [
      'Carbon morphology, purity target, and post-treatment yield',
      'Oxygen credit, contamination control, and concentrated CO2 vs DAC basis',
      'Market-size limits for premium grades versus generic specialty carbon',
    ],
  },
  {
    id: 'lime',
    label: 'Lime',
    family: 'calcination-minerals',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'resistive-calciner', label: 'Resistive electric calciner' },
      { value: 'indirect-heated', label: 'Indirect-heated calciner' },
    ],
    missingInputs: [
      'Limestone purity, moisture, and calciner boundary definition',
      'CO2 capture / compression basis and thermal-storage assumptions',
      'Hot-idle behavior for solar-only dispatch',
    ],
  },
  {
    id: 'cement',
    label: 'Cement',
    family: 'calcination-minerals',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'electrified-precalciner', label: 'Electrified precalciner' },
      { value: 'integrated-electric-kiln', label: 'Integrated electric kiln' },
    ],
    missingInputs: [
      'Raw meal chemistry, moisture, and precalciner vs kiln boundary',
      'CO2 capture / compression basis and clinker-factor assumption',
      'Thermal storage and hot-idle behavior under intermittent solar',
    ],
  },
  {
    id: 'steel',
    label: 'Steel',
    family: 'oxide-reduction',
    maturity: 'Exploratory',
    routeDependencies: {
      'h2-dri-eaf': ['electrolyzer'],
    },
    routeOptions: [
      { value: 'h2-dri-eaf', label: 'H2-DRI + EAF' },
      { value: 'flash-ironmaking', label: 'Flash ironmaking (developmental)' },
      { value: 'molten-oxide-electrolysis', label: 'Molten oxide electrolysis (speculative)' },
    ],
    missingInputs: [
      'DR-grade pellet quality, metallization target, and hot charge vs HBI',
      'Scrap fraction, oxygen use / credit, and grade-specific finishing',
      'Large H2 or HBI buffering assumptions for flexible solar operation',
    ],
  },
  {
    id: 'silicon',
    label: 'Silicon',
    family: 'oxide-reduction',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'electric-furnace', label: 'Electric furnace route' },
      { value: 'electrochemical-reduction', label: 'Electrochemical reduction (developmental)' },
    ],
    missingInputs: [
      'MG-Si vs solar-grade basis, quartz purity, and reductant mix',
      'Off-gas recovery and impurity-removal boundary',
      'Electrochemical scale-up and product-quality assumptions',
    ],
  },
  {
    id: 'aluminum',
    label: 'Aluminum',
    family: 'oxide-reduction',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'hall-heroult', label: 'Hall-Heroult style' },
      { value: 'novel-electrolysis', label: 'Novel electrolysis (developmental)' },
    ],
    missingInputs: [
      'Alumina-refinery boundary, bath chemistry, and casting losses',
      'Potline turndown, restart penalty, and anode-effect sensitivity',
      'Whether intermittent solar is realistic without major buffering',
    ],
  },
  {
    id: 'titanium',
    label: 'Titanium',
    family: 'oxide-reduction',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'kroll-like', label: 'Kroll-like route' },
      { value: 'ffc-cambridge', label: 'FFC-style electroreduction (developmental)' },
    ],
    missingInputs: [
      'TiCl4 boundary, Mg / MgCl2 recycle, and oxygen spec',
      'Sponge vs powder vs ingot basis with remelting boundary',
      'Batch cycle time versus continuous electroreduction assumptions',
    ],
  },
  {
    id: 'desalination',
    label: 'Desalination',
    family: 'water-systems',
    maturity: 'Exploratory',
    routeOptions: [
      { value: 'reverse-osmosis', label: 'Seawater reverse osmosis' },
      { value: 'electrodialysis', label: 'Brackish-water electrodialysis' },
      { value: 'thermal', label: 'Thermal MED / MSF' },
    ],
    missingInputs: [
      'Feed TDS, recovery ratio, and pretreatment intensity',
      'Energy-recovery-device assumptions and scaling / fouling behavior',
      'Brine discharge cost and whether the source is seawater or brackish',
    ],
  },
];

const EXPLORATORY_ROUTE_LIBRARY = {
  mtg: {
    routes: {
      'fixed-bed': {
        electricityKwhPerUnit: 250,
        capexPerAnnualUnit: 650,
        capexUnit: 'tpa',
        cyclingPenalty: 1.35,
        feedstocks: { methanolKg: 2273 },
        feedstockSummary: 'Needs MeOH',
        outputLabel: 'Hydrocarbons',
        outputUnit: 't',
        diagramInputs: { methanol: true },
      },
      'fluid-bed': {
        electricityKwhPerUnit: 180,
        capexPerAnnualUnit: 450,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: { methanolKg: 2273 },
        feedstockSummary: 'Needs MeOH',
        outputLabel: 'Hydrocarbons',
        outputUnit: 't',
        diagramInputs: { methanol: true },
      },
    },
  },
  carbonMonoxide: {
    routes: {
      plasma: {
        electricityKwhPerUnit: 5410,
        capexPerAnnualUnit: 750,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      rwgs: {
        electricityKwhPerUnit: 400,
        capexPerAnnualUnit: 250,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: { co2Kg: 1570, h2Kg: 71 },
        feedstockSummary: 'Needs DAC CO2 + H2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true, h2: true },
      },
      'low-temp-electrolysis': {
        electricityKwhPerUnit: 9360,
        capexPerAnnualUnit: 1500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      'soec-coelectrolysis': {
        electricityKwhPerUnit: 7000,
        capexPerAnnualUnit: 1650,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2 + heat',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
    },
  },
  ammonia: {
    routes: {
      'haber-bosch': {
        electricityKwhPerUnit: 1200,
        capexPerAnnualUnit: 600,
        capexUnit: 'tpa',
        cyclingPenalty: 1.5,
        feedstocks: { h2Kg: 176 },
        feedstockSummary: 'Needs H2 + N2',
        outputLabel: 'NH3',
        outputUnit: 't',
        diagramInputs: { h2: true },
      },
      electrochemical: {
        electricityKwhPerUnit: 7000,
        capexPerAnnualUnit: 3000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.1,
        feedstocks: {},
        feedstockSummary: 'Needs N2',
        outputLabel: 'NH3',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  specialtyCarbon: {
    routes: {
      'molten-carbonate': {
        electricityKwhPerUnit: 3500,
        capexPerAnnualUnit: 1200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.1,
        feedstocks: { co2Kg: 3670 },
        feedstockSummary: 'Needs CO2',
        outputLabel: 'Carbon',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      'graphene-grade': {
        electricityKwhPerUnit: 5000,
        capexPerAnnualUnit: 2200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { co2Kg: 3670 },
        feedstockSummary: 'Needs CO2',
        outputLabel: 'Carbon',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
    },
  },
  lime: {
    routes: {
      'resistive-calciner': {
        electricityKwhPerUnit: 890,
        capexPerAnnualUnit: 200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.35,
        feedstocks: {},
        feedstockSummary: 'Needs limestone',
        outputLabel: 'CaO',
        outputUnit: 't',
        diagramInputs: {},
      },
      'indirect-heated': {
        electricityKwhPerUnit: 980,
        capexPerAnnualUnit: 240,
        capexUnit: 'tpa',
        cyclingPenalty: 1.3,
        feedstocks: {},
        feedstockSummary: 'Needs limestone',
        outputLabel: 'CaO',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  cement: {
    routes: {
      'electrified-precalciner': {
        electricityKwhPerUnit: 1320,
        capexPerAnnualUnit: 275,
        capexUnit: 'tpa',
        cyclingPenalty: 1.4,
        feedstocks: {},
        feedstockSummary: 'Needs raw meal',
        outputLabel: 'Clinker eq.',
        outputUnit: 't',
        diagramInputs: {},
      },
      'integrated-electric-kiln': {
        electricityKwhPerUnit: 1500,
        capexPerAnnualUnit: 325,
        capexUnit: 'tpa',
        cyclingPenalty: 1.45,
        feedstocks: {},
        feedstockSummary: 'Needs raw meal',
        outputLabel: 'Clinker eq.',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  steel: {
    routes: {
      'h2-dri-eaf': {
        electricityKwhPerUnit: 3800,
        capexPerAnnualUnit: 700,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { h2Kg: 54 },
        feedstockSummary: 'Needs H2 + pellets',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: { h2: true },
      },
      'flash-ironmaking': {
        electricityKwhPerUnit: 3000,
        capexPerAnnualUnit: 550,
        capexUnit: 'tpa',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs ore + reductant',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: {},
      },
      'molten-oxide-electrolysis': {
        electricityKwhPerUnit: 5000,
        capexPerAnnualUnit: 2500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: {},
        feedstockSummary: 'Needs ore + flux',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  silicon: {
    routes: {
      'electric-furnace': {
        electricityKwhPerUnit: 12000,
        capexPerAnnualUnit: 900,
        capexUnit: 'tpa',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs quartz + C',
        outputLabel: 'Si',
        outputUnit: 't',
        diagramInputs: {},
      },
      'electrochemical-reduction': {
        electricityKwhPerUnit: 9000,
        capexPerAnnualUnit: 1800,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: {},
        feedstockSummary: 'Needs silica',
        outputLabel: 'Si',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  aluminum: {
    routes: {
      'hall-heroult': {
        electricityKwhPerUnit: 12500,
        capexPerAnnualUnit: 3500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.8,
        feedstocks: {},
        feedstockSummary: 'Needs alumina + anodes',
        outputLabel: 'Al',
        outputUnit: 't',
        diagramInputs: {},
      },
      'novel-electrolysis': {
        electricityKwhPerUnit: 11000,
        capexPerAnnualUnit: 5000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: {},
        feedstockSummary: 'Needs alumina',
        outputLabel: 'Al',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  titanium: {
    routes: {
      'kroll-like': {
        electricityKwhPerUnit: 50000,
        capexPerAnnualUnit: 8000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.4,
        feedstocks: {},
        feedstockSummary: 'Needs TiCl4 + Mg',
        outputLabel: 'Ti',
        outputUnit: 't',
        diagramInputs: {},
      },
      'ffc-cambridge': {
        electricityKwhPerUnit: 17000,
        capexPerAnnualUnit: 4000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: {},
        feedstockSummary: 'Needs TiO2',
        outputLabel: 'Ti',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  desalination: {
    routes: {
      'reverse-osmosis': {
        electricityKwhPerUnit: 2.2,
        capexPerAnnualUnit: 1500,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.05,
        feedstocks: {},
        feedstockSummary: 'Needs saline water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
      electrodialysis: {
        electricityKwhPerUnit: 0.8,
        capexPerAnnualUnit: 900,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.02,
        feedstocks: {},
        feedstockSummary: 'Needs brackish water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
      thermal: {
        electricityKwhPerUnit: 14,
        capexPerAnnualUnit: 3200,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs saline water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
    },
  },
};

const EXPLORATORY_MARKET_CONFIG = {
  mtg: {
    min: 200,
    max: 2000,
    step: 25,
    defaultValue: 900,
    label: 'Hydrocarbon sale price',
    unitLabel: '$/ton',
  },
  carbonMonoxide: {
    min: 100,
    max: 1500,
    step: 25,
    defaultValue: 600,
    label: 'CO sale price',
    unitLabel: '$/ton',
  },
  ammonia: {
    min: 200,
    max: 1500,
    step: 25,
    defaultValue: 700,
    label: 'Ammonia sale price',
    unitLabel: '$/ton',
  },
  specialtyCarbon: {
    min: 200,
    max: 5000,
    step: 50,
    defaultValue: 1500,
    label: 'Specialty carbon sale price',
    unitLabel: '$/ton',
  },
  lime: {
    min: 50,
    max: 300,
    step: 5,
    defaultValue: 120,
    label: 'Lime sale price',
    unitLabel: '$/ton',
  },
  cement: {
    min: 50,
    max: 250,
    step: 5,
    defaultValue: 100,
    label: 'Cement / clinker sale price',
    unitLabel: '$/ton',
  },
  steel: {
    min: 400,
    max: 1800,
    step: 10,
    defaultValue: 900,
    label: 'Steel sale price',
    unitLabel: '$/ton',
  },
  silicon: {
    min: 800,
    max: 5000,
    step: 50,
    defaultValue: 2200,
    label: 'Silicon sale price',
    unitLabel: '$/ton',
  },
  aluminum: {
    min: 1200,
    max: 5000,
    step: 25,
    defaultValue: 2500,
    label: 'Aluminum sale price',
    unitLabel: '$/ton',
  },
  titanium: {
    min: 4000,
    max: 18000,
    step: 100,
    defaultValue: 10000,
    label: 'Titanium sale price',
    unitLabel: '$/ton',
  },
  desalination: {
    min: 0.25,
    max: 10,
    step: 0.25,
    defaultValue: 1.5,
    label: 'Water sale price',
    unitLabel: '$/m3',
  },
};

const DEFAULT_STATE = {
  loadConfigTab: 'chemicals',

  dayMode: 'average',
  dayOfYear: 172,

  body: 'earth',
  solarProfileModel: 'earth',
  latitude: 35.05,
  longitude: -117.60,
  siteYieldMwhPerMwdcYear: 2050,
  siteYieldSource: 'preset',

  systemSizeMW: 1.0,
  panelEfficiency: 20,
  panelCostPerW: 0.20,
  panelDegradationAnnual: 0.65,
  mountingType: 'ew',
  bosCostPerW: 0.12,
  landCostPerAcre: 5000,
  sitePrepCostPerAcre: 15000,

  batteryEnabled: false,
  batteryCapacityMWh: 0.0,
  batteryCostPerKWh: 150,
  batteryEfficiency: 90,
  batteryCycles: 4000,
  chemicalSizingPercent: 100,

  aiComputeEnabled: false,
  aiReliabilityTarget: 99.9,
  aiTokenPricePerM: 3.0,
  aiMillionTokensPerMWh: 1000,
  aiGpuCapexPerKW: AI_COMPUTE_DEFAULTS.capexPerKW,
  aiAssetLifeYears: AI_COMPUTE_DEFAULTS.assetLifeYears,

  electrolyzerEnabled: true,
  electrolyzerEfficiency: 79,
  electrolyzerCapex: 100,
  electrolyzerAssetLife: 7,

  dacEnabled: true,
  dacEnergy: 3440,
  dacCapex: 450,
  dacAssetLife: 7,

  sabatierEnabled: true,
  sabatierConversion: 99,
  sabatierCapex: 120,
  sabatierAssetLife: 7,

  methanolEnabled: false,
  methaneFeedstockSplit: 50,
  methanolEfficiency: 80,
  methanolCapex: 385,
  methanolAssetLife: 7,

  methaneMarketPreset: 'terraform_commodity',
  exploratoryOmPercent: 4,

  mtgEnabled: false,
  mtgRoute: 'fixed-bed',
  mtgPriorityWeight: 100,
  mtgCapexBasis: EXPLORATORY_ROUTE_LIBRARY.mtg.routes['fixed-bed'].capexPerAnnualUnit,
  mtgMethanolSplit: 50,

  carbonMonoxideEnabled: false,
  carbonMonoxideRoute: 'plasma',
  carbonMonoxidePriorityWeight: 100,
  carbonMonoxideCapexBasis: EXPLORATORY_ROUTE_LIBRARY.carbonMonoxide.routes.plasma.capexPerAnnualUnit,

  ammoniaEnabled: false,
  ammoniaRoute: 'haber-bosch',
  ammoniaPriorityWeight: 100,
  ammoniaCapexBasis: EXPLORATORY_ROUTE_LIBRARY.ammonia.routes['haber-bosch'].capexPerAnnualUnit,

  specialtyCarbonEnabled: false,
  specialtyCarbonRoute: 'molten-carbonate',
  specialtyCarbonPriorityWeight: 100,
  specialtyCarbonCapexBasis: EXPLORATORY_ROUTE_LIBRARY.specialtyCarbon.routes['molten-carbonate'].capexPerAnnualUnit,

  limeEnabled: false,
  limeRoute: 'resistive-calciner',
  limePriorityWeight: 100,
  limeCapexBasis: EXPLORATORY_ROUTE_LIBRARY.lime.routes['resistive-calciner'].capexPerAnnualUnit,

  cementEnabled: false,
  cementRoute: 'electrified-precalciner',
  cementPriorityWeight: 100,
  cementCapexBasis: EXPLORATORY_ROUTE_LIBRARY.cement.routes['electrified-precalciner'].capexPerAnnualUnit,

  steelEnabled: false,
  steelRoute: 'h2-dri-eaf',
  steelPriorityWeight: 100,
  steelCapexBasis: EXPLORATORY_ROUTE_LIBRARY.steel.routes['h2-dri-eaf'].capexPerAnnualUnit,

  siliconEnabled: false,
  siliconRoute: 'electric-furnace',
  siliconPriorityWeight: 100,
  siliconCapexBasis: EXPLORATORY_ROUTE_LIBRARY.silicon.routes['electric-furnace'].capexPerAnnualUnit,

  aluminumEnabled: false,
  aluminumRoute: 'hall-heroult',
  aluminumPriorityWeight: 100,
  aluminumCapexBasis: EXPLORATORY_ROUTE_LIBRARY.aluminum.routes['hall-heroult'].capexPerAnnualUnit,

  titaniumEnabled: false,
  titaniumRoute: 'kroll-like',
  titaniumPriorityWeight: 100,
  titaniumCapexBasis: EXPLORATORY_ROUTE_LIBRARY.titanium.routes['kroll-like'].capexPerAnnualUnit,

  desalinationEnabled: false,
  desalinationRoute: 'reverse-osmosis',
  desalinationPriorityWeight: 100,
  desalinationCapexBasis: EXPLORATORY_ROUTE_LIBRARY.desalination.routes['reverse-osmosis'].capexPerAnnualUnit,

  methanePrice: 20,
  methanolPrice: 600,
  mtgPrice: EXPLORATORY_MARKET_CONFIG.mtg.defaultValue,
  carbonMonoxidePrice: EXPLORATORY_MARKET_CONFIG.carbonMonoxide.defaultValue,
  ammoniaPrice: EXPLORATORY_MARKET_CONFIG.ammonia.defaultValue,
  specialtyCarbonPrice: EXPLORATORY_MARKET_CONFIG.specialtyCarbon.defaultValue,
  limePrice: EXPLORATORY_MARKET_CONFIG.lime.defaultValue,
  cementPrice: EXPLORATORY_MARKET_CONFIG.cement.defaultValue,
  steelPrice: EXPLORATORY_MARKET_CONFIG.steel.defaultValue,
  siliconPrice: EXPLORATORY_MARKET_CONFIG.silicon.defaultValue,
  aluminumPrice: EXPLORATORY_MARKET_CONFIG.aluminum.defaultValue,
  titaniumPrice: EXPLORATORY_MARKET_CONFIG.titanium.defaultValue,
  desalinationPrice: EXPLORATORY_MARKET_CONFIG.desalination.defaultValue,

  policyMode: 'us_45v_tier4',
  customH2Credit: 0,
  customCo2Credit: 0,

  solarAssetLife: 30,
  analysisHorizonYears: 30,
  discountRate: 8,
  financingEnabled: false,
  debtSharePercent: 70,
  debtInterestRate: 6.5,
  debtTermYears: 15,
  debtFeePercent: 1.5,

  /** Annual M&O as % of applicable CAPEX (module+BOS, process equipment, battery). */
  solarOmPercent: 1.5,
  processOmPercent: 3,
  batteryOmPercent: 1.5,
};

const SLIDER_MARKERS = {
  chemicalSizingPercent: [
    { value: 70, label: 'Aggressive peak shaving' },
    { value: 85, label: 'Moderate peak shaving' },
    { value: 100, label: 'Full-capture default' },
  ],
  aiTokenPrice: [
    { value: 1, label: 'Low-value internal workload' },
    { value: 3, label: 'Balanced default case' },
    { value: 5, label: 'Higher-value inference mix' },
  ],
  aiTokensPerMWh: [
    { value: 400, label: 'Heavier models / lower throughput' },
    { value: 1000, label: 'Balanced default case' },
    { value: 1600, label: 'Lighter models / higher throughput' },
  ],
  methanePrice: [
    { value: 3, label: 'Low US spot gas' },
    { value: 10, label: 'Whitepaper commodity case' },
    { value: 20, label: 'Generic green methane case' },
    { value: 35, label: '2024 premium CH4 sale' },
  ],
  methanolPrice: [
    { value: 350, label: 'China spot price' },
    { value: 600, label: 'Europe' },
    { value: 1000, label: 'Green methanol' },
  ],
  batteryCost: [
    { value: 80, label: 'China' },
    { value: 150, label: 'Europe / US' },
  ],
  panelCost: [
    { value: 0.11, label: 'Mono-crystalline, no tariffs' },
    { value: 0.3, label: 'Mono-crystalline, with tariffs' },
  ],
  landCost: [
    { value: 2500, label: 'Cheap ag / desert land' },
    { value: 10000, label: 'Higher-value land' },
  ],
  sitePrepCost: [
    { value: 8000, label: 'Light clearing / grading' },
    { value: 20000, label: 'Heavier site prep' },
  ],
};
