/* ============================================
   Exploratory routes and market assumptions
   ============================================ */

const EXPLORATORY_ROUTE_LIBRARY = {
  mtg: {
    routes: {
      'fixed-bed': {
        electricityKwhPerUnit: 250,
        capexPerAnnualUnit: 650,
        capexUnit: 'tpa',
        cyclingPenalty: 1.35,
        supportsFeedBuffer: true,
        feedstocks: { methanolKg: 2273 },
        feedstockSummary: 'Needs MeOH',
        outputLabel: 'Hydrocarbons',
        outputUnit: 't',
        diagramInputs: { methanol: true },
      },
      'fluid-bed': {
        electricityKwhPerUnit: 180,
        capexPerAnnualUnit: 450,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        supportsFeedBuffer: true,
        feedstocks: { methanolKg: 2273 },
        feedstockSummary: 'Needs MeOH',
        outputLabel: 'Hydrocarbons',
        outputUnit: 't',
        diagramInputs: { methanol: true },
      },
    },
  },
  carbonMonoxide: {
    routes: {
      plasma: {
        electricityKwhPerUnit: 5410,
        capexPerAnnualUnit: 750,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      rwgs: {
        electricityKwhPerUnit: 400,
        capexPerAnnualUnit: 250,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        supportsFeedBuffer: true,
        feedstocks: { co2Kg: 1570, h2Kg: 71 },
        feedstockSummary: 'Needs DAC CO2 + H2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true, h2: true },
      },
      'low-temp-electrolysis': {
        electricityKwhPerUnit: 9360,
        capexPerAnnualUnit: 1500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      'soec-coelectrolysis': {
        electricityKwhPerUnit: 7000,
        capexPerAnnualUnit: 1650,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: { co2Kg: 1570 },
        feedstockSummary: 'Needs DAC CO2 + heat',
        outputLabel: 'CO',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
    },
  },
  ammonia: {
    routes: {
      'haber-bosch': {
        electricityKwhPerUnit: 1200,
        capexPerAnnualUnit: 600,
        capexUnit: 'tpa',
        cyclingPenalty: 1.5,
        supportsFeedBuffer: true,
        feedstocks: { h2Kg: 176 },
        feedstockSummary: 'Needs H2 + N2',
        outputLabel: 'NH3',
        outputUnit: 't',
        diagramInputs: { h2: true },
      },
      electrochemical: {
        electricityKwhPerUnit: 7000,
        capexPerAnnualUnit: 3000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.1,
        feedstocks: {},
        feedstockSummary: 'Needs N2',
        outputLabel: 'NH3',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  specialtyCarbon: {
    routes: {
      'molten-carbonate': {
        electricityKwhPerUnit: 3500,
        capexPerAnnualUnit: 1200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.1,
        feedstocks: { co2Kg: 3670 },
        feedstockSummary: 'Needs CO2',
        outputLabel: 'Carbon',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
      'graphene-grade': {
        electricityKwhPerUnit: 5000,
        capexPerAnnualUnit: 2200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { co2Kg: 3670 },
        feedstockSummary: 'Needs CO2',
        outputLabel: 'Carbon',
        outputUnit: 't',
        diagramInputs: { co2: true },
      },
    },
  },
  lime: {
    routes: {
      'resistive-calciner': {
        electricityKwhPerUnit: 890,
        capexPerAnnualUnit: 200,
        capexUnit: 'tpa',
        cyclingPenalty: 1.35,
        feedstocks: {},
        feedstockSummary: 'Needs limestone',
        outputLabel: 'CaO',
        outputUnit: 't',
        diagramInputs: {},
      },
      'indirect-heated': {
        electricityKwhPerUnit: 980,
        capexPerAnnualUnit: 240,
        capexUnit: 'tpa',
        cyclingPenalty: 1.3,
        feedstocks: {},
        feedstockSummary: 'Needs limestone',
        outputLabel: 'CaO',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  cement: {
    routes: {
      'electrified-precalciner': {
        electricityKwhPerUnit: 1320,
        capexPerAnnualUnit: 275,
        capexUnit: 'tpa',
        cyclingPenalty: 1.4,
        feedstocks: {},
        feedstockSummary: 'Needs raw meal',
        outputLabel: 'Clinker eq.',
        outputUnit: 't',
        diagramInputs: {},
      },
      'integrated-electric-kiln': {
        electricityKwhPerUnit: 1500,
        capexPerAnnualUnit: 325,
        capexUnit: 'tpa',
        cyclingPenalty: 1.45,
        feedstocks: {},
        feedstockSummary: 'Needs raw meal',
        outputLabel: 'Clinker eq.',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  steel: {
    routes: {
      'h2-dri-eaf': {
        electricityKwhPerUnit: 3800,
        capexPerAnnualUnit: 700,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: { h2Kg: 54 },
        feedstockSummary: 'Needs H2 + pellets',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: { h2: true },
      },
      'flash-ironmaking': {
        electricityKwhPerUnit: 3000,
        capexPerAnnualUnit: 550,
        capexUnit: 'tpa',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs ore + reductant',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: {},
      },
      'molten-oxide-electrolysis': {
        electricityKwhPerUnit: 5000,
        capexPerAnnualUnit: 2500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: {},
        feedstockSummary: 'Needs ore + flux',
        outputLabel: 'Steel',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  silicon: {
    routes: {
      'electric-furnace': {
        electricityKwhPerUnit: 12000,
        capexPerAnnualUnit: 900,
        capexUnit: 'tpa',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs quartz + C',
        outputLabel: 'Si',
        outputUnit: 't',
        diagramInputs: {},
      },
      'electrochemical-reduction': {
        electricityKwhPerUnit: 9000,
        capexPerAnnualUnit: 1800,
        capexUnit: 'tpa',
        cyclingPenalty: 1.15,
        feedstocks: {},
        feedstockSummary: 'Needs silica',
        outputLabel: 'Si',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  aluminum: {
    routes: {
      'hall-heroult': {
        electricityKwhPerUnit: 12500,
        capexPerAnnualUnit: 3500,
        capexUnit: 'tpa',
        cyclingPenalty: 1.8,
        feedstocks: {},
        feedstockSummary: 'Needs alumina + anodes',
        outputLabel: 'Al',
        outputUnit: 't',
        diagramInputs: {},
      },
      'novel-electrolysis': {
        electricityKwhPerUnit: 11000,
        capexPerAnnualUnit: 5000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.6,
        feedstocks: {},
        feedstockSummary: 'Needs alumina',
        outputLabel: 'Al',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  titanium: {
    routes: {
      'kroll-like': {
        electricityKwhPerUnit: 50000,
        capexPerAnnualUnit: 8000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.4,
        feedstocks: {},
        feedstockSummary: 'Needs TiCl4 + Mg',
        outputLabel: 'Ti',
        outputUnit: 't',
        diagramInputs: {},
      },
      'ffc-cambridge': {
        electricityKwhPerUnit: 17000,
        capexPerAnnualUnit: 4000,
        capexUnit: 'tpa',
        cyclingPenalty: 1.2,
        feedstocks: {},
        feedstockSummary: 'Needs TiO2',
        outputLabel: 'Ti',
        outputUnit: 't',
        diagramInputs: {},
      },
    },
  },
  desalination: {
    routes: {
      'reverse-osmosis': {
        electricityKwhPerUnit: 2.2,
        capexPerAnnualUnit: 1500,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.05,
        feedstocks: {},
        feedstockSummary: 'Needs saline water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
      electrodialysis: {
        electricityKwhPerUnit: 0.8,
        capexPerAnnualUnit: 900,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.02,
        feedstocks: {},
        feedstockSummary: 'Needs brackish water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
      thermal: {
        electricityKwhPerUnit: 14,
        capexPerAnnualUnit: 3200,
        capexUnit: 'm3pd',
        cyclingPenalty: 1.25,
        feedstocks: {},
        feedstockSummary: 'Needs saline water',
        outputLabel: 'Water',
        outputUnit: 'm3',
        diagramInputs: {},
      },
    },
  },
};

const EXPLORATORY_MARKET_CONFIG = {
  mtg: {
    min: 200,
    max: 2000,
    step: 25,
    defaultValue: 900,
    label: 'Hydrocarbon sale price',
    unitLabel: '$/ton',
  },
  carbonMonoxide: {
    min: 100,
    max: 1500,
    step: 25,
    defaultValue: 600,
    label: 'CO sale price',
    unitLabel: '$/ton',
  },
  ammonia: {
    min: 200,
    max: 1500,
    step: 25,
    defaultValue: 700,
    label: 'Ammonia sale price',
    unitLabel: '$/ton',
  },
  specialtyCarbon: {
    min: 200,
    max: 5000,
    step: 50,
    defaultValue: 1500,
    label: 'Specialty carbon sale price',
    unitLabel: '$/ton',
  },
  lime: {
    min: 50,
    max: 300,
    step: 5,
    defaultValue: 120,
    label: 'Lime sale price',
    unitLabel: '$/ton',
  },
  cement: {
    min: 50,
    max: 250,
    step: 5,
    defaultValue: 100,
    label: 'Cement / clinker sale price',
    unitLabel: '$/ton',
  },
  steel: {
    min: 400,
    max: 1800,
    step: 10,
    defaultValue: 900,
    label: 'Steel sale price',
    unitLabel: '$/ton',
  },
  silicon: {
    min: 800,
    max: 5000,
    step: 50,
    defaultValue: 2200,
    label: 'Silicon sale price',
    unitLabel: '$/ton',
  },
  aluminum: {
    min: 1200,
    max: 5000,
    step: 25,
    defaultValue: 2500,
    label: 'Aluminum sale price',
    unitLabel: '$/ton',
  },
  titanium: {
    min: 4000,
    max: 18000,
    step: 100,
    defaultValue: 10000,
    label: 'Titanium sale price',
    unitLabel: '$/ton',
  },
  desalination: {
    min: 0.25,
    max: 10,
    step: 0.25,
    defaultValue: 1.5,
    label: 'Water sale price',
    unitLabel: '$/m3',
  },
};
